/**
 * Builds `src/features/nutrition/foods.data.ts` from USDA FoodData Central.
 *
 *   bun scripts/build-foods.ts <path-to-FoodData_Central_sr_legacy_food_json_2018-04.json>
 *
 * The dataset (~200 MB unzipped) is NOT committed — download it from
 * https://fdc.nal.usda.gov/download-datasets (SR Legacy, JSON). It is public
 * domain (CC0); see src/features/nutrition/ATTRIBUTION.md.
 */
import { FOOD_CATEGORIES, type FoodCategory } from '../src/features/nutrition/foods';
import { CURATED_FOODS } from './foods/curated';

type FdcNutrient = { nutrient: { id: number }; amount?: number };
type FdcPortion = { gramWeight?: number };
type FdcFood = {
  fdcId: number;
  description: string;
  foodNutrients: FdcNutrient[];
  foodPortions?: FdcPortion[];
};

/** USDA nutrient ids → our per-100 g fields. */
const NUTRIENTS = {
  1008: 'kcal',
  1003: 'proteinG',
  1005: 'carbsG',
  1004: 'fatG',
  1079: 'fiberG',
} as const;

const [, , source] = process.argv;
if (!source) {
  console.error('usage: bun scripts/build-foods.ts <sr-legacy.json>');
  process.exit(1);
}

const { SRLegacyFoods } = (await Bun.file(source).json()) as { SRLegacyFoods: FdcFood[] };
const round1 = (n: number): number => Math.round(n * 10) / 10;

const rows = CURATED_FOODS.map((c) => {
  const hits = SRLegacyFoods.filter((f) => {
    const d = f.description.toLowerCase();
    return c.match.every((t) => d.includes(t)) && !c.exclude.some((t) => d.includes(t));
  });
  if (hits.length !== 1) {
    console.error(`✖ ${c.id}: expected exactly 1 USDA match, got ${hits.length}`);
    for (const h of hits.slice(0, 5)) console.error(`    ${h.description}`);
    process.exit(1);
  }
  if (!FOOD_CATEGORIES.includes(c.category as FoodCategory)) {
    console.error(`✖ ${c.id}: unknown category "${c.category}"`);
    process.exit(1);
  }
  const [food] = hits;
  const per100: Record<string, number> = { kcal: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 };
  for (const n of food.foodNutrients) {
    const key = NUTRIENTS[n.nutrient.id as keyof typeof NUTRIENTS];
    if (key && n.amount != null) per100[key] = round1(n.amount);
  }
  // The first household portion, as a sensible amount to prefill (grams only).
  const servingG = Math.round(food.foodPortions?.[0]?.gramWeight ?? 100);
  return {
    id: c.id,
    fdcId: food.fdcId,
    en: c.en,
    es: c.es,
    category: c.category,
    ...per100,
    servingG,
  };
});

const file = `/* eslint-disable */
// GENERATED by scripts/build-foods.ts — do not edit by hand.
// Nutrient values: USDA FoodData Central, SR Legacy (April 2018), public domain.
// Names and the selection: scripts/foods/curated.ts. Values are per 100 g.
import type { CatalogFood } from './foods';

export const FOODS: CatalogFood[] = ${JSON.stringify(rows, null, 2)};
`;
await Bun.write('src/features/nutrition/foods.data.ts', file);
console.log(`✔ ${rows.length} foods → src/features/nutrition/foods.data.ts`);
