/**
 * The curated staples list: WHICH foods ship, and what they are called in each
 * language. Every nutrient VALUE comes from USDA FoodData Central at build time
 * (`scripts/build-foods.ts`) — nothing here is a number, on purpose.
 *
 * `match` tokens must all appear in the USDA description (lower-cased) and no
 * `exclude` token may; the build fails unless exactly one food qualifies, so a
 * typo can never silently ship the wrong item.
 */
export type CuratedFood = {
  id: string;
  en: string;
  es: string;
  category: string;
  match: string[];
  exclude: string[];
};

export const CURATED_FOODS: CuratedFood[] = [
  {
    id: 'rice-white-raw',
    en: 'White rice, raw',
    es: 'Arroz blanco, crudo',
    category: 'grains',
    match: ['rice, white, long-grain, regular, raw, unenriched'],
    exclude: [],
  },
  {
    id: 'rice-white-cooked',
    en: 'White rice, cooked',
    es: 'Arroz blanco, cocido',
    category: 'grains',
    match: ['rice, white, long-grain, regular, unenriched, cooked without salt'],
    exclude: [],
  },
  {
    id: 'rice-brown-raw',
    en: 'Brown rice, raw',
    es: 'Arroz integral, crudo',
    category: 'grains',
    match: ['rice, brown, long-grain, raw'],
    exclude: [],
  },
  {
    id: 'rice-brown-cooked',
    en: 'Brown rice, cooked',
    es: 'Arroz integral, cocido',
    category: 'grains',
    match: ['rice, brown, long-grain, cooked'],
    exclude: [],
  },
  {
    id: 'oats-raw',
    en: 'Oats, dry',
    es: 'Avena, en seco',
    category: 'grains',
    match: ['cereals, oats, regular and quick, not fortified, dry'],
    exclude: [],
  },
  {
    id: 'pasta-raw',
    en: 'Pasta, dry',
    es: 'Pasta, en seco',
    category: 'grains',
    match: ['pasta, dry, unenriched'],
    exclude: ['whole', 'gluten', 'corn', 'spinach', 'protein'],
  },
  {
    id: 'pasta-cooked',
    en: 'Pasta, cooked',
    es: 'Pasta, cocida',
    category: 'grains',
    match: ['pasta, cooked, unenriched, without added salt'],
    exclude: ['whole', 'gluten', 'corn', 'spinach'],
  },
  {
    id: 'quinoa-raw',
    en: 'Quinoa, raw',
    es: 'Quinoa, cruda',
    category: 'grains',
    match: ['quinoa, uncooked'],
    exclude: [],
  },
  {
    id: 'quinoa-cooked',
    en: 'Quinoa, cooked',
    es: 'Quinoa, cocida',
    category: 'grains',
    match: ['quinoa, cooked'],
    exclude: [],
  },
  {
    id: 'bread-white',
    en: 'White bread',
    es: 'Pan blanco',
    category: 'grains',
    match: ['bread, white, commercially prepared (includes soft bread crumbs)'],
    exclude: [],
  },
  {
    id: 'bread-whole',
    en: 'Whole-wheat bread',
    es: 'Pan integral',
    category: 'grains',
    match: ['bread, whole-wheat, commercially prepared'],
    exclude: ['toasted'],
  },
  {
    id: 'tortilla-corn',
    en: 'Corn tortilla',
    es: 'Tortilla de maíz',
    category: 'grains',
    match: ['tortillas, ready-to-bake or -fry, corn'],
    exclude: ['without'],
  },
  {
    id: 'tortilla-flour',
    en: 'Flour tortilla',
    es: 'Tortilla de harina',
    category: 'grains',
    match: ['tortillas, ready-to-bake or -fry, flour, refrigerated'],
    exclude: [],
  },
  {
    id: 'potato-raw',
    en: 'Potato, raw',
    es: 'Papa, cruda',
    category: 'grains',
    match: ['potatoes, flesh and skin, raw'],
    exclude: [],
  },
  {
    id: 'potato-boiled',
    en: 'Potato, boiled',
    es: 'Papa, cocida',
    category: 'grains',
    match: ['potatoes, boiled, cooked without skin, flesh, without salt'],
    exclude: [],
  },
  {
    id: 'sweet-potato-raw',
    en: 'Sweet potato, raw',
    es: 'Camote, crudo',
    category: 'grains',
    match: ['sweet potato, raw, unprepared'],
    exclude: [],
  },
  {
    id: 'corn-sweet',
    en: 'Sweet corn',
    es: 'Elote (granos)',
    category: 'grains',
    match: ['corn, sweet, yellow, raw'],
    exclude: [],
  },
  {
    id: 'cornflakes',
    en: 'Corn flakes',
    es: 'Hojuelas de maíz',
    category: 'grains',
    match: ['cereals ready-to-eat, ralston corn flakes'],
    exclude: [],
  },
  {
    id: 'granola',
    en: 'Granola',
    es: 'Granola',
    category: 'grains',
    match: ['cereals ready-to-eat, granola, homemade'],
    exclude: [],
  },
  {
    id: 'chicken-breast-raw',
    en: 'Chicken breast, raw',
    es: 'Pechuga de pollo, cruda',
    category: 'protein',
    match: ['chicken, broiler or fryers, breast, skinless, boneless, meat only, raw'],
    exclude: [],
  },
  {
    id: 'chicken-breast-cooked',
    en: 'Chicken breast, cooked',
    es: 'Pechuga de pollo, cocida',
    category: 'protein',
    match: ['chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, grilled'],
    exclude: [],
  },
  {
    id: 'chicken-thigh-raw',
    en: 'Chicken thigh, raw',
    es: 'Muslo de pollo, crudo',
    category: 'protein',
    match: ['chicken, broilers or fryers, dark meat, thigh, meat only, raw'],
    exclude: [],
  },
  {
    id: 'turkey-breast',
    en: 'Turkey breast, raw',
    es: 'Pechuga de pavo, cruda',
    category: 'protein',
    match: ['turkey, retail parts, breast, meat only, raw'],
    exclude: [],
  },
  {
    id: 'beef-ground-90',
    en: 'Ground beef 90% lean, raw',
    es: 'Carne molida 90% magra, cruda',
    category: 'protein',
    match: ['beef, ground, 90% lean meat / 10% fat, raw'],
    exclude: [],
  },
  {
    id: 'beef-ground-80',
    en: 'Ground beef 80% lean, raw',
    es: 'Carne molida 80% magra, cruda',
    category: 'protein',
    match: ['beef, ground, 80% lean meat / 20% fat, raw'],
    exclude: [],
  },
  {
    id: 'beef-sirloin',
    en: 'Beef sirloin, raw',
    es: 'Sirloin de res, crudo',
    category: 'protein',
    match: ['beef, top sirloin, steak, separable lean only, trimmed to 1/8" fat, all grades, raw'],
    exclude: [],
  },
  {
    id: 'pork-loin',
    en: 'Pork loin, raw',
    es: 'Lomo de cerdo, crudo',
    category: 'protein',
    match: ['pork, fresh, loin, tenderloin, separable lean only, raw'],
    exclude: [],
  },
  {
    id: 'ham',
    en: 'Ham, sliced',
    es: 'Jamón, en rebanadas',
    category: 'protein',
    match: ['ham, sliced, regular (approximately 11% fat)'],
    exclude: [],
  },
  {
    id: 'bacon',
    en: 'Bacon, cooked',
    es: 'Tocino, cocido',
    category: 'protein',
    match: ['pork, cured, bacon, cooked, baked'],
    exclude: [],
  },
  {
    id: 'salmon',
    en: 'Salmon, raw',
    es: 'Salmón, crudo',
    category: 'protein',
    match: ['fish, salmon, atlantic, farmed, raw'],
    exclude: [],
  },
  {
    id: 'tuna-canned',
    en: 'Tuna, canned in water',
    es: 'Atún en agua',
    category: 'protein',
    match: ['fish, tuna, light, canned in water, drained solids'],
    exclude: ['without'],
  },
  {
    id: 'tilapia',
    en: 'Tilapia, raw',
    es: 'Tilapia, cruda',
    category: 'protein',
    match: ['fish, tilapia, raw'],
    exclude: [],
  },
  {
    id: 'shrimp',
    en: 'Shrimp, raw',
    es: 'Camarón, crudo',
    category: 'protein',
    match: ['crustaceans, shrimp, raw'],
    exclude: ['mixed'],
  },
  {
    id: 'egg-whole',
    en: 'Egg, whole',
    es: 'Huevo entero',
    category: 'protein',
    match: ['egg, whole, raw, fresh'],
    exclude: [],
  },
  {
    id: 'egg-white',
    en: 'Egg white',
    es: 'Clara de huevo',
    category: 'protein',
    match: ['egg, white, raw, fresh'],
    exclude: [],
  },
  {
    id: 'milk-whole',
    en: 'Whole milk',
    es: 'Leche entera',
    category: 'dairy',
    match: ['milk, whole, 3.25% milkfat, with added vitamin d'],
    exclude: [],
  },
  {
    id: 'milk-lowfat',
    en: 'Low-fat milk (1%)',
    es: 'Leche light (1%)',
    category: 'dairy',
    match: ['milk, lowfat, fluid, 1% milkfat, with added vitamin a and vitamin d'],
    exclude: ['protein'],
  },
  {
    id: 'milk-skim',
    en: 'Skim milk',
    es: 'Leche descremada',
    category: 'dairy',
    match: ['milk, nonfat, fluid, with added vitamin a and vitamin d (fat free or skim)'],
    exclude: [],
  },
  {
    id: 'yogurt-greek',
    en: 'Greek yogurt, plain nonfat',
    es: 'Yogur griego natural sin grasa',
    category: 'dairy',
    match: ['yogurt, greek, plain, nonfat'],
    exclude: [],
  },
  {
    id: 'yogurt-plain',
    en: 'Plain yogurt, whole milk',
    es: 'Yogur natural entero',
    category: 'dairy',
    match: ['yogurt, plain, whole milk'],
    exclude: ['greek'],
  },
  {
    id: 'cheese-fresco',
    en: 'Queso fresco',
    es: 'Queso fresco',
    category: 'dairy',
    match: ['cheese, fresh, queso fresco'],
    exclude: [],
  },
  {
    id: 'cheese-panela',
    en: 'Panela-style white cheese',
    es: 'Queso blanco tipo panela',
    category: 'dairy',
    match: ['cheese, white, queso blanco'],
    exclude: [],
  },
  {
    id: 'cheese-oaxaca',
    en: 'Oaxaca cheese',
    es: 'Queso Oaxaca',
    category: 'dairy',
    match: ['cheese, mexican, queso asadero'],
    exclude: [],
  },
  {
    id: 'cheese-cheddar',
    en: 'Cheddar cheese',
    es: 'Queso cheddar',
    category: 'dairy',
    match: ['cheese, cheddar (includes foods'],
    exclude: [],
  },
  {
    id: 'cheese-mozzarella',
    en: 'Mozzarella, part skim',
    es: 'Mozzarella semidescremada',
    category: 'dairy',
    match: ['cheese, mozzarella, part skim milk'],
    exclude: ['low moisture'],
  },
  {
    id: 'cottage',
    en: 'Cottage cheese, low-fat',
    es: 'Queso cottage bajo en grasa',
    category: 'dairy',
    match: ['cheese, cottage, lowfat, 2% milkfat'],
    exclude: [],
  },
  {
    id: 'butter',
    en: 'Butter',
    es: 'Mantequilla',
    category: 'dairy',
    match: ['butter, salted'],
    exclude: ['whipped', 'light'],
  },
  {
    id: 'cream',
    en: 'Sour cream',
    es: 'Crema ácida',
    category: 'dairy',
    match: ['cream, sour, cultured'],
    exclude: ['reduced'],
  },
  {
    id: 'whey',
    en: 'Whey protein powder',
    es: 'Proteína de suero en polvo',
    category: 'dairy',
    match: ['beverages, whey protein powder isolate'],
    exclude: [],
  },
  {
    id: 'beans-black-raw',
    en: 'Black beans, dry',
    es: 'Frijol negro, crudo',
    category: 'legumes',
    match: ['beans, black, mature seeds, raw'],
    exclude: [],
  },
  {
    id: 'beans-black-cooked',
    en: 'Black beans, cooked',
    es: 'Frijol negro, cocido',
    category: 'legumes',
    match: ['beans, black, mature seeds, cooked, boiled, without salt'],
    exclude: [],
  },
  {
    id: 'beans-pinto-cooked',
    en: 'Pinto beans, cooked',
    es: 'Frijol pinto, cocido',
    category: 'legumes',
    match: ['beans, pinto, mature seeds, cooked, boiled, without salt'],
    exclude: [],
  },
  {
    id: 'beans-refried',
    en: 'Refried beans',
    es: 'Frijoles refritos',
    category: 'legumes',
    match: ['refried beans, canned, traditional style'],
    exclude: ['reduced'],
  },
  {
    id: 'lentils-raw',
    en: 'Lentils, dry',
    es: 'Lentejas, crudas',
    category: 'legumes',
    match: ['lentils, raw'],
    exclude: ['pink', 'sprouted'],
  },
  {
    id: 'lentils-cooked',
    en: 'Lentils, cooked',
    es: 'Lentejas, cocidas',
    category: 'legumes',
    match: ['lentils, mature seeds, cooked, boiled, without salt'],
    exclude: [],
  },
  {
    id: 'chickpeas-cooked',
    en: 'Chickpeas, cooked',
    es: 'Garbanzos, cocidos',
    category: 'legumes',
    match: ['chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt'],
    exclude: [],
  },
  {
    id: 'tofu',
    en: 'Tofu, firm',
    es: 'Tofu firme',
    category: 'legumes',
    match: ['tofu, raw, firm, prepared with calcium sulfate'],
    exclude: [],
  },
  {
    id: 'banana',
    en: 'Banana',
    es: 'Plátano',
    category: 'fruit',
    match: ['bananas, raw'],
    exclude: [],
  },
  {
    id: 'apple',
    en: 'Apple',
    es: 'Manzana',
    category: 'fruit',
    match: ['apples, raw, with skin'],
    exclude: [],
  },
  {
    id: 'orange',
    en: 'Orange',
    es: 'Naranja',
    category: 'fruit',
    match: ['oranges, raw, all commercial varieties'],
    exclude: [],
  },
  {
    id: 'strawberry',
    en: 'Strawberries',
    es: 'Fresas',
    category: 'fruit',
    match: ['strawberries, raw'],
    exclude: [],
  },
  {
    id: 'blueberry',
    en: 'Blueberries',
    es: 'Arándanos',
    category: 'fruit',
    match: ['blueberries, raw'],
    exclude: [],
  },
  {
    id: 'mango',
    en: 'Mango',
    es: 'Mango',
    category: 'fruit',
    match: ['mangos, raw'],
    exclude: [],
  },
  {
    id: 'papaya',
    en: 'Papaya',
    es: 'Papaya',
    category: 'fruit',
    match: ['papayas, raw'],
    exclude: [],
  },
  {
    id: 'pineapple',
    en: 'Pineapple',
    es: 'Piña',
    category: 'fruit',
    match: ['pineapple, raw, all varieties'],
    exclude: [],
  },
  {
    id: 'watermelon',
    en: 'Watermelon',
    es: 'Sandía',
    category: 'fruit',
    match: ['watermelon, raw'],
    exclude: [],
  },
  {
    id: 'grapes',
    en: 'Grapes',
    es: 'Uvas',
    category: 'fruit',
    match: ['grapes, red or green (european type, such as thompson seedless), raw'],
    exclude: [],
  },
  {
    id: 'lime',
    en: 'Lime',
    es: 'Limón',
    category: 'fruit',
    match: ['limes, raw'],
    exclude: [],
  },
  {
    id: 'avocado',
    en: 'Avocado',
    es: 'Aguacate',
    category: 'fruit',
    match: ['avocados, raw, all commercial varieties'],
    exclude: [],
  },
  {
    id: 'broccoli',
    en: 'Broccoli',
    es: 'Brócoli',
    category: 'vegetables',
    match: ['broccoli, raw'],
    exclude: ['chinese', 'leaves', 'stalks', 'flower'],
  },
  {
    id: 'spinach',
    en: 'Spinach',
    es: 'Espinaca',
    category: 'vegetables',
    match: ['spinach, raw'],
    exclude: ['mustard', 'new zealand'],
  },
  {
    id: 'lettuce',
    en: 'Romaine lettuce',
    es: 'Lechuga romana',
    category: 'vegetables',
    match: ['lettuce, cos or romaine, raw'],
    exclude: [],
  },
  {
    id: 'tomato',
    en: 'Tomato',
    es: 'Jitomate',
    category: 'vegetables',
    match: ['tomatoes, red, ripe, raw, year round average'],
    exclude: [],
  },
  {
    id: 'onion',
    en: 'Onion',
    es: 'Cebolla',
    category: 'vegetables',
    match: ['onions, raw'],
    exclude: ['spring', 'sweet', 'young', 'welsh'],
  },
  {
    id: 'carrot',
    en: 'Carrot',
    es: 'Zanahoria',
    category: 'vegetables',
    match: ['carrots, raw'],
    exclude: ['baby'],
  },
  {
    id: 'cucumber',
    en: 'Cucumber',
    es: 'Pepino',
    category: 'vegetables',
    match: ['cucumber, with peel, raw'],
    exclude: [],
  },
  {
    id: 'bell-pepper',
    en: 'Bell pepper, red',
    es: 'Pimiento rojo',
    category: 'vegetables',
    match: ['peppers, sweet, red, raw'],
    exclude: [],
  },
  {
    id: 'zucchini',
    en: 'Zucchini',
    es: 'Calabacita',
    category: 'vegetables',
    match: ['squash, summer, zucchini, includes skin, raw'],
    exclude: [],
  },
  {
    id: 'nopal',
    en: 'Nopales',
    es: 'Nopales',
    category: 'vegetables',
    match: ['nopales, raw'],
    exclude: [],
  },
  {
    id: 'mushroom',
    en: 'Mushrooms',
    es: 'Champiñones',
    category: 'vegetables',
    match: ['mushrooms, white, raw'],
    exclude: [],
  },
  {
    id: 'cauliflower',
    en: 'Cauliflower',
    es: 'Coliflor',
    category: 'vegetables',
    match: ['cauliflower, raw'],
    exclude: ['green'],
  },
  {
    id: 'green-beans',
    en: 'Green beans',
    es: 'Ejotes',
    category: 'vegetables',
    match: ['beans, snap, green, raw'],
    exclude: [],
  },
  {
    id: 'jalapeno',
    en: 'Jalapeño',
    es: 'Chile jalapeño',
    category: 'vegetables',
    match: ['peppers, jalapeno, raw'],
    exclude: [],
  },
  {
    id: 'olive-oil',
    en: 'Olive oil',
    es: 'Aceite de oliva',
    category: 'fats',
    match: ['oil, olive, salad or cooking'],
    exclude: [],
  },
  {
    id: 'canola-oil',
    en: 'Canola oil',
    es: 'Aceite de canola',
    category: 'fats',
    match: ['oil, canola'],
    exclude: ['industrial', 'high oleic', 'and '],
  },
  {
    id: 'almonds',
    en: 'Almonds',
    es: 'Almendras',
    category: 'fats',
    match: ['nuts, almonds'],
    exclude: ['oil', 'roasted', 'blanched', 'butter', 'honey', 'paste'],
  },
  {
    id: 'walnuts',
    en: 'Walnuts',
    es: 'Nueces',
    category: 'fats',
    match: ['nuts, walnuts, english'],
    exclude: [],
  },
  {
    id: 'peanuts',
    en: 'Peanuts',
    es: 'Cacahuates',
    category: 'fats',
    match: ['peanuts, all types, raw'],
    exclude: [],
  },
  {
    id: 'peanut-butter',
    en: 'Peanut butter',
    es: 'Crema de cacahuate',
    category: 'fats',
    match: ['peanut butter, smooth style, without salt'],
    exclude: [],
  },
  {
    id: 'chia',
    en: 'Chia seeds',
    es: 'Semillas de chía',
    category: 'fats',
    match: ['seeds, chia seeds, dried'],
    exclude: [],
  },
  {
    id: 'flaxseed',
    en: 'Flaxseed',
    es: 'Linaza',
    category: 'fats',
    match: ['seeds, flaxseed'],
    exclude: [],
  },
  {
    id: 'sugar',
    en: 'Sugar',
    es: 'Azúcar',
    category: 'other',
    match: ['sugars, granulated'],
    exclude: [],
  },
  {
    id: 'honey',
    en: 'Honey',
    es: 'Miel',
    category: 'other',
    match: ['honey'],
    exclude: [
      'cereal',
      'roll',
      'ham',
      'mustard',
      'nuts',
      'bar',
      'graham',
      'dressing',
      'bread',
      'cracker',
      'snack',
      'candies',
      'loaf',
      ',',
    ],
  },
  {
    id: 'chocolate-dark',
    en: 'Dark chocolate 70–85%',
    es: 'Chocolate amargo 70–85%',
    category: 'other',
    match: ['chocolate, dark, 70-85% cacao solids'],
    exclude: [],
  },
  {
    id: 'orange-juice',
    en: 'Orange juice',
    es: 'Jugo de naranja',
    category: 'other',
    match: ['orange juice, raw'],
    exclude: [],
  },
  {
    id: 'cola',
    en: 'Cola soft drink',
    es: 'Refresco de cola',
    category: 'other',
    match: ['beverages, carbonated, cola, regular'],
    exclude: [],
  },
  {
    id: 'beer',
    en: 'Beer, regular',
    es: 'Cerveza',
    category: 'other',
    match: ['alcoholic beverage, beer, regular, all'],
    exclude: [],
  },
  {
    id: 'salsa',
    en: 'Salsa, ready-to-serve',
    es: 'Salsa (lista para servir)',
    category: 'other',
    match: ['sauce, salsa, ready-to-serve'],
    exclude: [],
  },
  {
    id: 'mayonnaise',
    en: 'Mayonnaise',
    es: 'Mayonesa',
    category: 'other',
    match: ['salad dressing, mayonnaise, regular'],
    exclude: [],
  },
  {
    id: 'tortilla-chips',
    en: 'Tortilla chips',
    es: 'Totopos',
    category: 'other',
    match: ['snacks, tortilla chips, plain, white corn, salted'],
    exclude: [],
  },
  {
    id: 'oats-cooked',
    en: 'Oatmeal, cooked',
    es: 'Avena, cocida',
    category: 'grains',
    match: ['cereals, oats, regular and quick, unenriched, cooked with water'],
    exclude: [],
  },
  {
    id: 'bagel',
    en: 'Bagel',
    es: 'Bagel',
    category: 'grains',
    match: ['bagels, plain, enriched, with calcium propionate'],
    exclude: ['toasted'],
  },
  {
    id: 'asparagus',
    en: 'Asparagus',
    es: 'Espárragos',
    category: 'vegetables',
    match: ['asparagus, raw'],
    exclude: [],
  },
  {
    id: 'cabbage',
    en: 'Cabbage',
    es: 'Col',
    category: 'vegetables',
    match: ['cabbage, raw'],
    exclude: ['red', 'savoy', 'chinese'],
  },
  {
    id: 'celery',
    en: 'Celery',
    es: 'Apio',
    category: 'vegetables',
    match: ['celery, raw'],
    exclude: [],
  },
  {
    id: 'eggplant',
    en: 'Eggplant',
    es: 'Berenjena',
    category: 'vegetables',
    match: ['eggplant, raw'],
    exclude: [],
  },
  {
    id: 'arugula',
    en: 'Arugula',
    es: 'Arúgula',
    category: 'vegetables',
    match: ['arugula, raw'],
    exclude: [],
  },
  {
    id: 'pumpkin',
    en: 'Pumpkin',
    es: 'Calabaza',
    category: 'vegetables',
    match: ['pumpkin, raw'],
    exclude: ['leaves', 'flowers', 'fish'],
  },
  {
    id: 'peas',
    en: 'Green peas',
    es: 'Chícharos',
    category: 'vegetables',
    match: ['peas, green, raw'],
    exclude: [],
  },
  {
    id: 'beet',
    en: 'Beetroot',
    es: 'Betabel',
    category: 'vegetables',
    match: ['beets, raw'],
    exclude: [],
  },
  {
    id: 'garlic',
    en: 'Garlic',
    es: 'Ajo',
    category: 'vegetables',
    match: ['garlic, raw'],
    exclude: [],
  },
  {
    id: 'cilantro',
    en: 'Cilantro',
    es: 'Cilantro',
    category: 'vegetables',
    match: ['coriander (cilantro) leaves, raw'],
    exclude: [],
  },
  {
    id: 'kiwi',
    en: 'Kiwi',
    es: 'Kiwi',
    category: 'fruit',
    match: ['kiwifruit, green, raw'],
    exclude: [],
  },
  {
    id: 'cantaloupe',
    en: 'Cantaloupe melon',
    es: 'Melón',
    category: 'fruit',
    match: ['melons, cantaloupe, raw'],
    exclude: [],
  },
  {
    id: 'peach',
    en: 'Peach',
    es: 'Durazno',
    category: 'fruit',
    match: ['peaches, yellow, raw'],
    exclude: [],
  },
  {
    id: 'raspberry',
    en: 'Raspberries',
    es: 'Frambuesas',
    category: 'fruit',
    match: ['raspberries, raw'],
    exclude: [],
  },
  {
    id: 'cream-cheese',
    en: 'Cream cheese',
    es: 'Queso crema',
    category: 'dairy',
    match: ['cheese, cream'],
    exclude: ['low fat', 'fat free', 'spread', 'frosting'],
  },
  {
    id: 'ricotta',
    en: 'Ricotta, part skim',
    es: 'Ricotta semidescremada',
    category: 'dairy',
    match: ['cheese, ricotta, part skim milk'],
    exclude: [],
  },
  {
    id: 'parmesan',
    en: 'Parmesan',
    es: 'Parmesano',
    category: 'dairy',
    match: ['cheese, parmesan, hard'],
    exclude: [],
  },
  {
    id: 'gouda',
    en: 'Gouda',
    es: 'Gouda',
    category: 'dairy',
    match: ['cheese, gouda'],
    exclude: [],
  },
  {
    id: 'turkey-deli',
    en: 'Turkey breast, sliced',
    es: 'Pechuga de pavo en rebanadas',
    category: 'protein',
    match: ['turkey breast, sliced, prepackaged'],
    exclude: [],
  },
  {
    id: 'salmon-smoked',
    en: 'Smoked salmon',
    es: 'Salmón ahumado',
    category: 'protein',
    match: ['fish, salmon, chinook, smoked, (lox), regular'],
    exclude: [],
  },
  {
    id: 'cod',
    en: 'Cod, raw',
    es: 'Bacalao, crudo',
    category: 'protein',
    match: ['fish, cod, atlantic, raw'],
    exclude: [],
  },
  {
    id: 'tuna-fresh',
    en: 'Tuna, fresh',
    es: 'Atún fresco',
    category: 'protein',
    match: ['fish, tuna, fresh, yellowfin, raw'],
    exclude: [],
  },
  {
    id: 'sardines',
    en: 'Sardines, canned',
    es: 'Sardinas en lata',
    category: 'protein',
    match: ['fish, sardine, atlantic, canned in oil, drained solids with bone'],
    exclude: [],
  },
  {
    id: 'turkey-ground',
    en: 'Ground turkey 93% lean, raw',
    es: 'Pavo molido 93% magro, crudo',
    category: 'protein',
    match: ['turkey, ground, 93% lean, 7% fat, raw'],
    exclude: [],
  },
  {
    id: 'pork-chop',
    en: 'Pork chop, raw',
    es: 'Chuleta de cerdo, cruda',
    category: 'protein',
    match: ['pork, fresh, loin, center rib (chops or roasts), boneless, separable lean only, raw'],
    exclude: [],
  },
  {
    id: 'tempeh',
    en: 'Tempeh',
    es: 'Tempeh',
    category: 'legumes',
    match: ['tempeh'],
    exclude: ['cooked'],
  },
  {
    id: 'edamame',
    en: 'Edamame',
    es: 'Edamame',
    category: 'legumes',
    match: ['edamame, frozen, prepared'],
    exclude: [],
  },
  {
    id: 'soymilk',
    en: 'Soy milk, unsweetened',
    es: 'Leche de soya sin azúcar',
    category: 'dairy',
    match: ['soymilk (all flavors), unsweetened, with added calcium, vitamins a and d'],
    exclude: [],
  },
  {
    id: 'almond-milk',
    en: 'Almond milk, unsweetened',
    es: 'Leche de almendra sin azúcar',
    category: 'dairy',
    match: ['beverages, almond milk, unsweetened, shelf stable'],
    exclude: [],
  },
  {
    id: 'coconut-milk',
    en: 'Coconut milk, canned',
    es: 'Leche de coco en lata',
    category: 'dairy',
    match: ['nuts, coconut milk, canned'],
    exclude: [],
  },
  {
    id: 'hummus',
    en: 'Hummus',
    es: 'Hummus',
    category: 'legumes',
    match: ['hummus, commercial'],
    exclude: [],
  },
  {
    id: 'soy-textured',
    en: 'Textured soy',
    es: 'Soya texturizada',
    category: 'legumes',
    match: ['soy flour, defatted'],
    exclude: [],
  },
  {
    id: 'seitan',
    en: 'Seitan (wheat gluten)',
    es: 'Seitán (gluten de trigo)',
    category: 'legumes',
    match: ['vital wheat gluten'],
    exclude: [],
  },
  {
    id: 'almond-butter',
    en: 'Almond butter',
    es: 'Crema de almendra',
    category: 'fats',
    match: ['nuts, almond butter, plain, without salt added'],
    exclude: [],
  },
  {
    id: 'tahini',
    en: 'Tahini',
    es: 'Tahini',
    category: 'fats',
    match: ['seeds, sesame butter, tahini, from roasted and toasted kernels'],
    exclude: [],
  },
  {
    id: 'sesame',
    en: 'Sesame seeds',
    es: 'Ajonjolí',
    category: 'fats',
    match: ['seeds, sesame seeds, whole, dried'],
    exclude: [],
  },
  {
    id: 'pumpkin-seeds',
    en: 'Pumpkin seeds',
    es: 'Pepitas de calabaza',
    category: 'fats',
    match: ['seeds, pumpkin and squash seed kernels, dried'],
    exclude: [],
  },
  {
    id: 'hemp-seeds',
    en: 'Hemp seeds',
    es: 'Semillas de cáñamo',
    category: 'fats',
    match: ['seeds, hemp seed, hulled'],
    exclude: [],
  },
  {
    id: 'coconut-dried',
    en: 'Shredded coconut',
    es: 'Coco rallado',
    category: 'fats',
    match: ['nuts, coconut meat, dried (desiccated), not sweetened'],
    exclude: [],
  },
  {
    id: 'coconut-oil',
    en: 'Coconut oil',
    es: 'Aceite de coco',
    category: 'fats',
    match: ['oil, coconut'],
    exclude: [],
  },
  {
    id: 'maple-syrup',
    en: 'Maple syrup',
    es: 'Jarabe de maple',
    category: 'other',
    match: ['syrups, maple'],
    exclude: ['canadian', 'table blends'],
  },
  {
    id: 'soy-sauce',
    en: 'Soy sauce',
    es: 'Salsa de soya',
    category: 'other',
    match: ['soy sauce made from soy and wheat (shoyu)'],
    exclude: ['low sodium'],
  },
  {
    id: 'vinegar-balsamic',
    en: 'Balsamic vinegar',
    es: 'Vinagre balsámico',
    category: 'other',
    match: ['vinegar, balsamic'],
    exclude: [],
  },
  {
    id: 'cinnamon',
    en: 'Cinnamon',
    es: 'Canela',
    category: 'other',
    match: ['spices, cinnamon, ground'],
    exclude: [],
  },
];
